# Generated by Django 5.2.17 on 2026-09-21 10:35

import apps.core.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='blog/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp']), apps.core.validators.validate_image_size], verbose_name='cover image (upload)')),
                ('cover_image', models.CharField(blank=True, help_text='Used when no image is uploaded.', max_length=500, validators=[apps.core.validators.validate_link], verbose_name='cover image URL')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated', max_length=500)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reading_time', models.PositiveIntegerField(default=5, help_text='Minutes')),
            ],
            options={
                'verbose_name': 'blog post',
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Leave 0 to keep creation order.')),
                ('name', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('date', models.CharField(help_text='Free text, e.g. "2022"', max_length=50)),
                ('link', models.CharField(blank=True, max_length=500, validators=[apps.core.validators.validate_link], verbose_name='credential link')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Leave 0 to keep creation order.')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='courses/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp']), apps.core.validators.validate_image_size])),
                ('image_url', models.CharField(blank=True, help_text='Used when no image is uploaded.', max_length=500, validators=[apps.core.validators.validate_link], verbose_name='image URL')),
                ('link', models.CharField(blank=True, max_length=500, validators=[apps.core.validators.validate_link], verbose_name='course link')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Leave 0 to keep creation order.')),
                ('institution', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'education',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Leave 0 to keep creation order.')),
                ('company', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('start_date', models.CharField(help_text='Free text, e.g. "2021" or "Jan 2021"', max_length=50)),
                ('end_date', models.CharField(blank=True, help_text='e.g. "2024" or "Present"', max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Leave 0 to keep creation order.')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='gallery/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp']), apps.core.validators.validate_image_size])),
                ('image_url', models.CharField(blank=True, help_text='Used when no image is uploaded. Provide one or the other.', max_length=500, validators=[apps.core.validators.validate_link], verbose_name='image URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'gallery item',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Leave 0 to keep creation order.')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('technologies', models.CharField(blank=True, help_text='Comma-separated, e.g. React, Node.js, PostgreSQL', max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='projects/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp']), apps.core.validators.validate_image_size])),
                ('image_url', models.CharField(blank=True, help_text='Used when no image is uploaded.', max_length=500, validators=[apps.core.validators.validate_link], verbose_name='image URL')),
                ('github_link', models.CharField(blank=True, max_length=500, validators=[apps.core.validators.validate_link], verbose_name='GitHub link')),
                ('live_demo_link', models.CharField(blank=True, max_length=500, validators=[apps.core.validators.validate_link], verbose_name='live demo link')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Leave 0 to keep creation order.')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp']), apps.core.validators.validate_image_size], verbose_name='profile image (upload)')),
                ('profile_image_url', models.CharField(blank=True, help_text='Used when no image is uploaded.', max_length=500, validators=[apps.core.validators.validate_link], verbose_name='profile image URL')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('website', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Leave 0 to keep creation order.')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(help_text='e.g. Frontend, Backend, Database', max_length=100)),
                ('proficiency', models.PositiveIntegerField(help_text='0 – 100', validators=[django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhatIDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Leave 0 to keep creation order.')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(help_text='Lucide icon name: Globe, Terminal, Database, …', max_length=50)),
                ('items', models.TextField(help_text='Comma-separated, e.g. React, Next.js, TypeScript')),
            ],
            options={
                'verbose_name': 'what I do card',
                'verbose_name_plural': 'what I do cards',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
