# Generated by Django 5.2.17 on 2026-09-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=120, verbose_name='role / company')),
                ('text', models.TextField(max_length=1500, verbose_name='testimony')),
                ('is_approved', models.BooleanField(db_index=True, default=False, help_text='Only approved testimonies appear on the public site.', verbose_name='approved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='submitted at')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
